config/routes.rb
# This code is free software; you can redistribute it and/or modify it under
# the terms of the new BSD License.
#
# Copyright (c) 2012-2014, Sebastian Staudt

Rails.application.routes.draw do

  resources :repositories, path: 'repos', only: [],
            constraints: { repository_id: /[0-9A-Za-z_-]+?\/[0-9A-Za-z_-]+/ } do
    resources :formulae, only: :browse, path: 'browse' do
      get ':letter(/:page)', action: :browse, on: :collection,
          as: :letter,
          constraints: { letter: /[A-Za-z]/, page: /\d+/, format: 'html' }
    end

    resources :formulae, only: :browse, path: 'search' do
      get '(:search(/:page))', action: :search, on: :collection,
          as: :search,
          constraints: { page: /\d+/, search: /[^\/]+/, format: 'html' }
    end

    resources :formula, controller: :formulae, only: :show,
              constraints: { id: /.*/, format: 'html' }

    scope format: true, :constraints => { :format => 'atom' } do
      get '/feed' => 'formulae#feed', as: :feed
    end
  end

  resources :formulae, only: :browse, path: 'browse' do
    get ':letter(/:page)', action: :browse, on: :collection,
        as: :letter,
        constraints: { letter: /[A-Za-z]/, page: /\d+/, format: 'html' }
  end

  resources :formulae, only: :browse, path: 'search' do
    get '(:search(/:page))', action: :search, on: :collection,
        as: :search,
        constraints: { page: /\d+/, search: /[^\/]+/, format: 'html' }
  end

  resources :formula, controller: :formulae, only: :show,
            constraints: { id: /.*/, format: 'html' }

  scope format: true, :constraints => { :format => 'atom' } do
    get '/feed' => 'formulae#feed', as: :feed
  end

  scope format: true, :constraints => { :format => 'xml' } do
    get '/sitemap' => 'application#sitemap', as: :sitemap
  end

  root to: 'application#index'

  get '*url', to: 'application#not_found', format: false

  delete '/', to: 'application#forbidden', format: false
  delete '*url', to: 'application#forbidden', format: false
  post '/', to: 'application#forbidden', format: false
  post '*url', to: 'application#forbidden', format: false
  put '/', to: 'application#forbidden', format: false
  put '*url', to: 'application#forbidden', format: false
  match '/', via: :options, to: 'application#forbidden', format: false
  match '*url', via: :options, to: 'application#forbidden', format: false

end

app/controllers/formulae_controller.rb
# This code is free software; you can redistribute it and/or modify it under
# the terms of the new BSD License.
#
# Copyright (c) 2012-2014, Sebastian Staudt

require 'text'

class FormulaeController < ApplicationController

  before_filter :select_repository
  before_filter :letters, only: [ :browse, :search ]

  def browse
    letter = params[:letter]
    @title = "Browse formulae – #{letter.upcase}"
    @title << " – #{@repository.name}" unless @repository.main?

    @formulae = @repository.formulae.letter(letter).
            where(removed: false).order_by([:name, :asc]).
            page(params[:page]).per 30

    fresh_when etag: @repository.sha, public: true
  end

  def feed
    @revisions = @repository.revisions.order_by([:date, :desc]).limit 50

    respond_to do |format|
      format.atom
    end

    fresh_when etag: @repository.sha, public: true
  end

  def search
    return not_found if params[:search].nil? || params[:search].empty?

    term = params[:search]
    @title = "Search for: #{term}"
    @title << " in #{@repository.name}" unless @repository.main?
    @formulae = @repository.formulae.
      where name: /#{Regexp.escape term}/i, removed: false

    if @formulae.size == 1 && term == @formulae.first.name
      if @repository.main?
        redirect_to formula_path(@formulae.first)
      else
        redirect_to repository_formula_path(@repository.name, @formulae.first)
      end
      return
    end

    @formulae = @formulae.sort_by do |formula|
      Text::Levenshtein.distance(formula.name, term) +
      Text::Levenshtein.distance(formula.name[0..term.size - 1], term)
    end
    @formulae = Kaminari.paginate_array(@formulae).
            page(params[:page]).per 30

    respond_to do |format|
      format.html { render 'formulae/browse' }
    end

    fresh_when etag: @repository.sha, public: true
  end

  def show
    formula_id = "#{repository_id}/#{params[:id]}"
    @formula = Formula.find formula_id
    if @formula.nil?
      formula = @repository.formulae.all_in(aliases: [params[:id]]).first
      unless formula.nil?
        if @repository.main?
          redirect_to formula
        else
          redirect_to repository_formula_path(@repository.name, formula)
        end
        return
      end
      raise Mongoid::Errors::DocumentNotFound.new(Formula, [], params[:id])
    end
    @title = @formula.name.dup
    @title << " – #{@repository.name}" unless @repository.main?
    @revisions = @formula.revisions.includes(:author).order_by %i{date desc}

    fresh_when etag: @revisions.first.sha, public: true
  end

  private

  def letters
    @letters = ('A'..'Z').select do |letter|
      @repository.formulae.letter(letter).where(removed: false).exists?
    end
  end

  def repository_id
    @repository_id ||= params[:repository_id] || Repository::MAIN
  end

  def select_repository
    main_repo_url = "/repos/#{Repository::MAIN}/"
    if request.url.match main_repo_url
      redirect_to '/' + request.url.split(main_repo_url, 2)[1]
      return
    end

    @repository = Repository.where(name: /^#{repository_id}$/i).
            only(:_id, :name, :sha, :updated_at).first
    if @repository.nil?
      raise Mongoid::Errors::DocumentNotFound.new Repository, [], repository_id
    end

    if @repository.name != repository_id
      redirect_to request.url.sub "/repos/#{repository_id}", "/repos/#{@repository.name}"
    end
  end

end

app/views/formulae/_formula.html.erb
<div class="formula <%= cycle 'even', 'odd' %><%= ' removed' if formula.removed? %>">
  <%= formula_link formula %><br>
  Current version: <strong class="version spec-<%= formula.best_spec %>">
    <%= formula.version %>
  </strong><br>
  Homepage: <%= link_to formula.homepage, formula.homepage %>
</div>

app/views/formulae/_search.html.erb
<form action="<%= search_formulae_path %>" id="search-form">
  <%= icon 'search', '', class: 'search-icon' if local_assigns[:with_icon] %>
  <input id="search" name="search" type="text" placeholder="<%= params[:search] || 'search…'.html_safe %>" />
</form>

app/views/formulae/browse.html.erb
<h1>Package listing</h1>

<% if @repository.main? %>
  This is a listing of all packages available via the Homebrew package manager
  for MacOS X.
<% else %>
  This is a listing of all Homebrew packages available via the alternative
  repository
  <%= link_to @repository.name, "https://github.com/#{@repository.name}" %>.
<% end %>

<%= link_to icon('rss-square'), @repository.feed_link, class: 'feed-link', title: t('.feed_title', name: @repository.name) %>

<%= render partial: 'search', locals: { with_icon: true } %>

<ul id="letters">
  <% ('A'..'Z').each do |letter|
    letter_url = @repository.main? ? letter_formulae_path(letter.downcase) : letter_repository_formulae_path(@repository.name, letter.downcase) %>
    <li>
      <% if @letters.include? letter
        letter_class = 'current' if letter == (params[:letter] || '').upcase %>
        <%= link_to_unless_current letter, letter_url, class: letter_class do %>
          <span class="current"><%= letter %></span>
        <% end %>
      <% else %>
        <%= letter %>
      <% end %>
    </li>
  <% end %>
</ul>

<% if @formulae.total_count == 0 %>
  <div class="error">Sorry, no formulae are matching your search.</div>
<% else
  page_params = { id: nil }
  if params.key?(:search) && !params[:search].empty?
    page_params[:use_route] = :search_formulae
  end
  pagination = paginate @formulae, params: page_params %>

  <% content_for :kaminari do %>
    <%= rel_next_prev_link_tags @formulae %>
  <% end %>

  <%= pagination %>

  <div class="listing">
    <% @formulae.each do |formula| %>
      <%= render partial: 'formula', locals: { formula: formula } %>
    <% end %>
  </div>

  <%= pagination %>
<% end %>

app/views/formulae/show.html.erb
<h1><%= @formula.name %></h1>
<% unless @repository.main? %>
  <div class="subtitle">in <%= link_to @repository.name, letter_repository_formulae_path(@repository, @repository.first_letter), class: 'repo' %></div>
<% end %>

<div id="basic">
  <% if @formula.removed? %>
    <h2 class="removed">Formula was removed<br>Last version was:
  <% else %>
    <h2>Current versions:
  <% end %>
  <div class="versions">
    <% unless @formula.stable_version.nil? %>
      <strong class="version spec-stable"><%= @formula.stable_version %></strong>
    <% end %>
    <% unless @formula.devel_version.nil? %>
     <strong class="version spec-devel"><%= @formula.devel_version %></strong>
    <% end %>
    <% unless @formula.head_version.nil? %>
      <strong class="version spec-head"><%= @formula.head_version %></strong>
    <% end %>
  </div></h2>
  <% unless @formula.homepage.nil? %>
    <h2>Homepage: <em><%= link_to @formula.homepage, @formula.homepage %></em></h2>
  <% end %>
  <% unless (@formula.aliases || []).empty? %>
    Also known as: <strong><%= safe_join @formula.aliases, '</strong>, <strong>'.html_safe %></strong><br>
  <% end %>
  <% if @formula.keg_only? %>
    <strong>This formula is <abbr title="A keg-only formula won't be symlinked automatically.">keg-only</abbr>.</strong><br>
  <% end %>
</div>

<% unless @formula.deps.empty? %>
  <div id="deps">
    <h2>Dependencies</h2>
      <%= t '.deps_html', name: @formula.name, count: @formula.deps.size %>
    <ul>
      <% @formula.deps.order_by([:name, :asc]).each do |dep| %>
        <%= render partial: 'formula', locals: { formula: dep } %>
      <% end %>
    </ul>
  </div>
<% end %>

<% reset_cycle %>

<% unless @formula.revdeps.where(removed: false).empty? %>
  <div id="revdeps">
    <h2>Reverse dependencies</h2>
    <%= t '.revdeps_html', name: @formula.name, count: @formula.revdeps.size %>
    <ul>
      <% @formula.revdeps.where(removed: false).order_by([:name, :asc]).each do |revdep| %>
        <%= render partial: 'formula', locals: { formula: revdep } %>
      <% end %>
    </ul>
  </div>
<% end %>

<% unless @revisions.empty? %>
<div id="history">
  <h2>Formula history</h2>
  <table>
  <% @revisions.each_with_index do |rev, i| %>
    <tr<% if i == 0 %> class="current"<% elsif i > 9 %> class="hidden"<% end %>>
      <td class="author">
        <%= link_to '', "https://github.com/#{@repository.name}/commit/#{rev.sha}##{@formula.path}" %>
        <%= rev.author.name %></td>
      <td class="subject">
        <%= link_to '', "https://github.com/#{@repository.name}/commit/#{rev.sha}##{@formula.path}" %>
        <%= rev.subject %>
      </td>
      <td class="date">
        <%= link_to '', "https://github.com/#{@repository.name}/commit/#{rev.sha}##{@formula.path}" %>
        <%= timestamp rev.date %>
      </td>
    </tr>
    <% if i == 9 %>
    <tr class="show-all">
      <td colspan="3">
        <%= icon 'long-arrow-down' %>
        Show all revisions of this formula
        <%= icon 'long-arrow-down' %>
      </td>
    </tr>
    <% end %>
  <% end %>
  </table>
</div>
<% end %>