config/routes.rb
# This code is free software; you can redistribute it and/or modify it under
# the terms of the new BSD License.
#
# Copyright (c) 2012-2014, Sebastian Staudt

Rails.application.routes.draw do

  resources :repositories, path: 'repos', only: [],
            constraints: { repository_id: /[0-9A-Za-z_-]+?\/[0-9A-Za-z_-]+/ } do
    resources :formulae, only: :browse, path: 'browse' do
      get ':letter(/:page)', action: :browse, on: :collection,
          as: :letter,
          constraints: { letter: /[A-Za-z]/, page: /\d+/, format: 'html' }
    end

    resources :formulae, only: :browse, path: 'search' do
      get '(:search(/:page))', action: :search, on: :collection,
          as: :search,
          constraints: { page: /\d+/, search: /[^\/]+/, format: 'html' }
    end

    resources :formula, controller: :formulae, only: :show,
              constraints: { id: /.*/, format: 'html' }

    scope format: true, :constraints => { :format => 'atom' } do
      get '/feed' => 'formulae#feed', as: :feed
    end
  end

  resources :formulae, only: :browse, path: 'browse' do
    get ':letter(/:page)', action: :browse, on: :collection,
        as: :letter,
        constraints: { letter: /[A-Za-z]/, page: /\d+/, format: 'html' }
  end

  resources :formulae, only: :browse, path: 'search' do
    get '(:search(/:page))', action: :search, on: :collection,
        as: :search,
        constraints: { page: /\d+/, search: /[^\/]+/, format: 'html' }
  end

  resources :formula, controller: :formulae, only: :show,
            constraints: { id: /.*/, format: 'html' }

  scope format: true, :constraints => { :format => 'atom' } do
    get '/feed' => 'formulae#feed', as: :feed
  end

  scope format: true, :constraints => { :format => 'xml' } do
    get '/sitemap' => 'application#sitemap', as: :sitemap
  end

  root to: 'application#index'

  get '*url', to: 'application#not_found', format: false

  delete '/', to: 'application#forbidden', format: false
  delete '*url', to: 'application#forbidden', format: false
  post '/', to: 'application#forbidden', format: false
  post '*url', to: 'application#forbidden', format: false
  put '/', to: 'application#forbidden', format: false
  put '*url', to: 'application#forbidden', format: false
  match '/', via: :options, to: 'application#forbidden', format: false
  match '*url', via: :options, to: 'application#forbidden', format: false

end

app/controllers/application_controller.rb
# This code is free software; you can redistribute it and/or modify it under
# the terms of the new BSD License.
#
# Copyright (c) 2012-2015, Sebastian Staudt

class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception
  rescue_from Mongoid::Errors::DocumentNotFound, with: :not_found

  def index
    main_page

    respond_to do |format|
      format.html { render 'application/index' }
      format.any { render nothing: true, status: :not_found }
    end

    fresh_when etag: Repository.main.sha, public: true
  end

  def error_page
    Airbrake.notify $! if defined? Airbrake

    respond_to do |format|
      format.html { render 'application/500', status: :internal_server_error }
      format.any { render nothing: true, status: :internal_server_error }
    end

    headers.delete 'ETag'
    expires_in 5.minutes
  end

  def forbidden
    respond_to do |format|
      format.any { render nothing: true, status: :forbidden }
    end
  end

  def not_found
    flash.now[:error] = 'The page you requested does not exist.'
    main_page

    respond_to do |format|
      format.html { render 'application/index', status: :not_found }
      format.any { render nothing: true, status: :not_found }
    end

    headers.delete 'ETag'
    expires_in 5.minutes
  end

  def sitemap
    @repository = Repository.only(:_id, :sha, :updated_at).main

    respond_to do |format|
      format.xml
    end

    fresh_when etag: @repository.sha, public: true
  end

  private

  def main_page
    @alt_repos = Repository.only(:_id, :date, :name, :sha, :updated_at).order_by([:name, :asc]).to_a
    @repository = @alt_repos.find { |repo| repo.name == Repository::MAIN }
    @alt_repos -= [ @repository ]

    @added = @repository.formulae.with_size(revision_ids: 1).
            order_by(%i{date desc}).
            only(:_id, :devel_version, :head_version, :name, :repository_id, :stable_version).
            limit 5

    @updated = @repository.formulae.where(removed: false).
            not.with_size(revision_ids: 1).
            order_by(%i{date desc}).
            only(:_id, :devel_version, :head_version, :name, :repository_id, :stable_version).
            limit 5

    @removed = @repository.formulae.where(removed: true).
            order_by(%i{date desc}).
            only(:_id, :name, :repository_id).
            limit 5
  end

end

app/helpers/application_helper.rb
# This code is free software; you can redistribute it and/or modify it under
# the terms of the new BSD License.
#
# Copyright (c) 2012-2013, Sebastian Staudt

module ApplicationHelper

  def formula_link(formula, options = {})
    options = { class: 'formula' }.merge options
    url_options = formula.in_main? ? formula : [ formula.repository, formula ]
    link_to formula.name, url_for(url_options), options
  end

  def timestamp(time)
    options = {
      class: 'timeago',
      datetime: time.getutc.iso8601
    }
    content_tag :time, l(time, format: :long), options
  end

  def title
    title = 'braumeister.org'
    title = "#@title – #{title}" unless @title.nil?
    title
  end

end

app/views/application/500.html.erb
<h1>Someone spilled our beer!</h1>
<p>Something went horribly wrong will you tried to access our pages.
But fear not, we have been notified of the problem.</p>
<p>Please try again in a few seconds. If the problem persists, feel
free to contact
<a href="https://twitter.com/braumeister_org">@braumeister_org</a> on
Twitter.</p>

app/views/application/_recent.html.erb
<div class="formula <%= cycle 'even', 'odd' %>">
  <%= formula_link formula %>
  <strong class="version spec-<%= formula.best_spec %>">
    <%= formula.version %>
  </strong><br>
</div>

app/views/application/index.html.erb
<div id="home">
  <strong>braumeister.org</strong> is an online package browser for
  <%= link_to 'Homebrew', 'http://brew.sh' %> – the MacOS X
  package manager.<br>
  For more information on how to install and use Homebrew see its homepage.

  <%= link_to 'Browse all formulae', letter_formulae_path('a'), class: 'center' %>

  <h2><%= icon 'search' %> Search a formula:</h2>
  <%= render partial: 'formulae/search' %>
</div>

<div class="recently-added">
  <h3><%= icon 'plus-square' %> Recently added formulae</h3>
  <div class="listing">
    <% @added.each do |formula| %>
      <%= render partial: 'recent', locals: { formula: formula } %>
    <% end %>
  </div>
</div>

<% reset_cycle %>

<div class="recently-updated">
  <h3><%= icon 'pencil-square' %> Recently updated formulae</h3>
  <div class="listing">
    <% @updated.each do |formula| %>
      <%= render partial: 'recent', locals: { formula: formula } %>
    <% end %>
  </div>
</div>

<div class="recently-removed">
  <h5><%= icon 'minus-square' %> Recently removed formulae</h5>
  <%= @removed.map { |f| formula_link f }.join(', ').html_safe %>
</div>

<div id="timestamps">
  The repository has been updated <%= timestamp @repository.updated_at %>.<br>
  The last change happened <%= timestamp @repository.date %>.<br>
  Current Git commit SHA: <%= link_to @repository.sha, "https://github.com/#{@repository.name}/tree/#{@repository.sha}" %>
</div>

<% unless @alt_repos.empty? %>
  <div id="alternatives">
    <h2><%= icon 'code-fork' %> Alternative repositories:</h2>
    <div class="listing">
    <% @alt_repos.each do |repo| %>
      <div class="repo"><%= link_to repo.name, letter_repository_formulae_path(repo, repo.first_letter) %></div>
    <% end %>
    </div>
  </div>
<% end %>