config/routes.rb
# This code is free software; you can redistribute it and/or modify it under
# the terms of the new BSD License.
#
# Copyright (c) 2012-2014, Sebastian Staudt

Rails.application.routes.draw do

  resources :repositories, path: 'repos', only: [],
            constraints: { repository_id: /[0-9A-Za-z_-]+?\/[0-9A-Za-z_-]+/ } do
    resources :formulae, only: :browse, path: 'browse' do
      get ':letter(/:page)', action: :browse, on: :collection,
          as: :letter,
          constraints: { letter: /[A-Za-z]/, page: /\d+/, format: 'html' }
    end

    resources :formulae, only: :browse, path: 'search' do
      get '(:search(/:page))', action: :search, on: :collection,
          as: :search,
          constraints: { page: /\d+/, search: /[^\/]+/, format: 'html' }
    end

    resources :formula, controller: :formulae, only: :show,
              constraints: { id: /.*/, format: 'html' }

    scope format: true, :constraints => { :format => 'atom' } do
      get '/feed' => 'formulae#feed', as: :feed
    end
  end

  resources :formulae, only: :browse, path: 'browse' do
    get ':letter(/:page)', action: :browse, on: :collection,
        as: :letter,
        constraints: { letter: /[A-Za-z]/, page: /\d+/, format: 'html' }
  end

  resources :formulae, only: :browse, path: 'search' do
    get '(:search(/:page))', action: :search, on: :collection,
        as: :search,
        constraints: { page: /\d+/, search: /[^\/]+/, format: 'html' }
  end

  resources :formula, controller: :formulae, only: :show,
            constraints: { id: /.*/, format: 'html' }

  scope format: true, :constraints => { :format => 'atom' } do
    get '/feed' => 'formulae#feed', as: :feed
  end

  scope format: true, :constraints => { :format => 'xml' } do
    get '/sitemap' => 'application#sitemap', as: :sitemap
  end

  root to: 'application#index'

  get '*url', to: 'application#not_found', format: false

  delete '/', to: 'application#forbidden', format: false
  delete '*url', to: 'application#forbidden', format: false
  post '/', to: 'application#forbidden', format: false
  post '*url', to: 'application#forbidden', format: false
  put '/', to: 'application#forbidden', format: false
  put '*url', to: 'application#forbidden', format: false
  match '/', via: :options, to: 'application#forbidden', format: false
  match '*url', via: :options, to: 'application#forbidden', format: false

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html itemscope itemtype="http://schema.org/WebPage" lang="en">
<head>
  <title><%= title %></title>

  <%= auto_discovery_link_tag :atom, feed_path(format: :atom) %>
  <%= include_jquery defer: true %>
  <%= javascript_include_tag 'application', defer: true %>
  <%= stylesheet_link_tag 'application' %>
  <%= csrf_meta_tag %>

  <link rel="search" type="application/opensearchdescription+xml" title="braumeister.org" href="/opensearch.xml">
  <%= favicon_link_tag 'data:image/x-icon;,', type: 'image/x-icon' %>
  <%= yield :kaminari %>

  <meta http-equiv="content-type" content="text/html;charset=UTF-8">
  <meta itemprop="name" content="braumeister.org">
  <meta itemprop="description" content="An online package browser for Homebrew, the MacOS package manager.">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <script src="http://platform.twitter.com/widgets.js" type="text/javascript"></script>

  <script type="text/javascript">
    /* <![CDATA[ */
        (function() {
            var s = document.createElement('script'), t = document.getElementsByTagName('script')[0];
            s.type = 'text/javascript';
            s.async = true;
            s.src = 'http://api.flattr.com/js/0.6/load.js?mode=auto';
            t.parentNode.insertBefore(s, t);
        })();
    /* ]]> */
  </script>

  <% if Rails.env == 'production' %>
  <script type="text/javascript">
      var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-258817-9']);
    _gaq.push(['_trackPageview']);
    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();
  </script>
  <% end %>
</head>
<body<% unless @repository.nil? || @repository.main? %> data-repository="<%= @repository.name %>"<% end %>>
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    <a href="https://github.com/koraktor/braumeister.org">
        <img id="github-ribbon"
             src="http://s3.amazonaws.com/github/ribbons/forkme_left_orange_ff7600.png"
             alt="Fork me on GitHub">
    </a>
    <div id="header">
        <div id="social">
            <div class="g-plusone"
                 data-href="http://braumeister.org"
                 data-size="tall"></div>
            <a href="http://twitter.com/share" class="twitter-share-button"
               data-count="vertical"
               data-text="See information about Mac packages available via Homebrew – "
               data-url="http://braumeister.org">
                Tweet
            </a>
            <div class="fb-like" data-href="http://braumeister.org" data-width="55" data-height="62" data-colorscheme="light" data-layout="box_count" data-action="like" data-show-faces="true" data-send="false"></div>
            <a class="FlattrButton" style="display: none" href="http://braumeister.org"></a>
        </div>
        <%= link_to 'Braumeister', root_path %>
    </div>
    <div id="content">
        <% if flash[:error] %>
            <div id="flash-error"><%= flash[:error].html_safe %></div>
        <% end %>
        <% if flash[:notice] %>
            <div id="flash-notice"><%= flash[:notice].html_safe %></div>
        <% end %>
        <%= yield %>
    </div>
    <div id="footer">
        © 2012-2015 —
        <a href="https://plus.google.com/109586181974940228820?rel=author">
        Sebastian Staudt</a><br>
        Follow <a href="https://twitter.com/braumeister_org">@braumeister_org</a>
        on Twitter.
    </div>
    <script type="text/javascript">
      (function() {
        var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
        po.src = 'https://apis.google.com/js/plusone.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
      })();
    </script>
</body>
</html>